name: laxminarayan_portfolio
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.0
  connectivity_plus: ^2.2.1
  device_info_plus: ^3.2.2
  email_validator: ^2.0.1
  flutter_multi_formatter: ^2.5.1
  flutter_screenutil: ^5.5.2
  flutter_svg: ^1.0.3
  flutter_secure_storage: ^5.0.2
  flutter_staggered_grid_view: ^0.4.1
  expandable_page_view: ^1.0.13
  fluttericon: ^2.0.0
  fluttertoast: ^8.0.9
  get: ^4.6.1
  google_fonts: ^2.3.1
  intl: ^0.17.0
  internet_connection_checker: ^0.0.1+3
  flutter_phoenix: ^1.0.0
  http: ^0.13.4
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  url_launcher: ^6.1.2
  logger: ^1.1.0
  firebase_core: ^1.16.0
  firebase_auth: ^3.3.17
 

  cupertino_icons: ^1.0.2
  google_sign_in: ^5.3.1
  google_sign_in_web: ^0.10.1+2
  url_strategy: ^0.2.0
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
      - family: Poppins
        fonts:
          - asset: assets/fonts/Lato-Regular.ttf
          - asset: assets/fonts/Lato-Black.ttf
          - asset: assets/fonts/Lato-Bold.ttf
          - asset: assets/fonts/Lato-Light.ttf
          - asset: assets/fonts/Lato-Thin.ttf
          - asset: assets/fonts/Oswald-Bold.ttf
          - asset: assets/fonts/Oswald-ExtraLight.ttf
          - asset: assets/fonts/Oswald-Light.ttf
          - asset: assets/fonts/Oswald-Medium.ttf
          - asset: assets/fonts/Oswald-Regular.ttf
          - asset: assets/fonts/Oswald-SemiBold.ttf
          - asset: assets/fonts/Roboto-Bold.ttf
          - asset: assets/fonts/Roboto-Light.ttf
          - asset: assets/fonts/Roboto-Medium.ttf
          - asset: assets/fonts/Roboto-Regular.ttf
          - asset: assets/fonts/Roboto-Black.ttf